base_output_dir: data/full
pyspi_config: configs/config.yaml
pyspi_subset: default
normalise: true
rng_seed: 110305
save_heatmap: false
threads: 8

defaults:
  M_values: [4, 9, 16]
  T_values: [100, 400, 900, 1600]
  instances: [0, 1, 2]

mts_classes:
  - name: "VAR(1)"
    labels: ["linear", "gaussian", "var"]
    generator: "var"
    include_base_variant: false
    instances: [0]
    base_params:
      phi: 0.94
      coupling: 0.67
      noise_std: 0.1
      transients: 100
    variants:
      - name: "phi=0.33"
        params: {phi: 0.33}
      - name: "phi=0.66"
        params: {phi: 0.66}
      - name: "phi=0.99"
        params: {phi: 0.99}

  - name: "CML"
    labels: ["nonlinear", "cml"]
    generator: "cml_logistic"
    include_base_variant: false
    M_values: [9, 16, 25]
    T_values: [100, 400, 900, 1600]
    base_params:
      alpha: 1.7522
      eps: 0.00115
      delta: "3"
      transients: 0
    variants:
      - name: "spatiotemporal_intermittency_I"
        params:
          alpha: 1.7522
          eps: 0.00115
          delta: "1,3,12"
          transients: 0

  - name: "Kuramoto"
    labels: ["oscillator", "kuramoto", "phase"]
    generator: "kuramoto"
    instances: [0]
    base_params:
      dt: 0.1
      k: -4
      omega_mean: 0.5
      omega_std: 0.3
      eta: 0.0
      transients: 100
    include_base_variant: false
    instances: [0]
    variants:
      - name: "all_to_all"
        params:
          connectivity: "all-to-all"
      - name: "bidirectional_list"
        params:
          connectivity: "bidirectional-list"
      - name: "grid_four"
        params:
          connectivity: "grid-four"

  - name: "GaussianNoise"
    labels: ["noise", "gaussian"]
    generator: "gaussian_noise"
    base_params: {}

  - name: "CauchyNoise"
    labels: ["noise", "cauchy", "heavy-tail"]
    generator: "cauchy_noise"
    base_params: {}
