base_output_dir: data/full
pyspi_config: configs/blended_config.yaml
pyspi_subset: default
normalise: false
rng_seed: 110305
save_heatmap: false
threads: 8

defaults:
  M_values: [4, 8, 16, 32]
  T_values: [500, 1000, 2000]
  instances: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
  single_instance_M_values: [64]
  single_instance_T_values: [1000]
  single_instance_instances: [0]

mts_classes:
  - name: "VAR(1)"
    labels: ["linear", "gaussian", "var"]
    generator: "varma"
    include_base_variant: false
    base_params:
      phi: 0.6
      coupling: 0.2
      ma_phi: 0.0
      ma_coupling: 0.0
      noise_std: 0.1
      transients: 100
      zscore: true
    variants:
      - name: "phi-0.6_coupling-0.2"
        params: {}  

  - name: "VAR(1)-shuffled"
    labels: ["linear", "gaussian", "var", "shuffled"]
    generator: "varma_shuffled"
    include_base_variant: false
    base_params:
      phi: 0.6
      coupling: 0.2
      ma_phi: 0.0
      ma_coupling: 0.0
      noise_std: 0.1
      transients: 100
      zscore: true
    variants:
      - name: "phi-0.6_coupling-0.2"
        params: {}  
  
  - name: "CML"
    labels: ["nonlinear", "cml"]
    generator: "cml_logistic"
    include_base_variant: false
    base_params:
      alpha: 1.7522
      eps: 0.00115
      delta: "3"
      transients: 0
      zscore: true
    variants:
      - name: "spatiotemporal_intermittency_I"
        params:
          alpha: 1.7522
          eps: 0.00115
          delta: "1,3,12"
          transients: 0

  - name: "Kuramoto"
    labels: ["oscillator", "kuramoto", "phase"]
    generator: "kuramoto"
    base_params:
      dt: 0.1
      k: -4
      omega_mean: 0.5
      omega_std: 0.3
      eta: 0.0
      transients: 100
      zscore: true
    include_base_variant: false
    variants:
      - name: 
        params:
          connectivity: "all-to-all"

  - name: "GaussianNoise"
    labels: ["noise", "gaussian"]
    generator: "gaussian_noise"
    base_params:
      zscore: true

  - name: "CauchyNoise"
    labels: ["noise", "cauchy", "heavy-tail"]
    generator: "cauchy_noise"
    base_params:
      zscore: false
