# Basic statistics
.statistics.basic:
  # Covariance
  Covariance:
    labels:
      - undirected
      - linear
      - signed
      - multivariate
      - contemporaneous
    dependencies:
    configs:
      - estimator: EmpiricalCovariance
      - estimator: EllipticEnvelope
      - estimator: GraphicalLasso
      - estimator: GraphicalLassoCV
      - estimator: LedoitWolf
      - estimator: MinCovDet
      - estimator: OAS
      - estimator: ShrunkCovariance
      - estimator: EmpiricalCovariance
        squared: True
      - estimator: EllipticEnvelope
        squared: True
      - estimator: GraphicalLasso
        squared: True
      - estimator: GraphicalLassoCV
        squared: True
      - estimator: LedoitWolf
        squared: True
      - estimator: MinCovDet
        squared: True
      - estimator: OAS
        squared: True
      - estimator: ShrunkCovariance
        squared: True

  # Precision
  Precision:
    labels:
      - undirected
      - linear
      - signed
      - multivariate
      - contemporaneous
    dependencies:
    configs:
      - estimator: EmpiricalCovariance
      - estimator: EllipticEnvelope
      - estimator: GraphicalLasso
      - estimator: GraphicalLassoCV
      - estimator: LedoitWolf
      - estimator: MinCovDet
      - estimator: OAS
      - estimator: ShrunkCovariance
      - estimator: EmpiricalCovariance
        squared: True
      - estimator: EllipticEnvelope
        squared: True
      - estimator: GraphicalLasso
        squared: True
      - estimator: GraphicalLassoCV
        squared: True
      - estimator: LedoitWolf
        squared: True
      - estimator: MinCovDet
        squared: True
      - estimator: OAS
        squared: True
      - estimator: ShrunkCovariance
        squared: True

  # Spearman's correlation coefficient
  SpearmanR:
    labels:
      - undirected
      - nonlinear
      - signed
      - bivariate
      - contemporaneous
    dependencies:
    configs:
      - squared: True
      - squared: False

  # Kendall's rank correlation coefficient
  KendallTau:
    labels:
      - undirected
      - nonlinear
      - signed
      - bivariate
      - contemporaneous
    dependencies:
    configs:
      - squared: True
      - squared: False

  # statistics based on cross-correlation (squared means we square the xcorr, not the output)
  CrossCorrelation:
    labels:
      - undirected
      - linear
      - signed/unsigned
      - bivariate
      - time-dependent
    dependencies:
    configs:
      - statistic: "max"

      - statistic: "max"
        squared: True

      - statistic: "mean"

      - statistic: "mean"
        squared: True

      - statistic: "mean"
        sigonly: False

      - statistic: "mean"
        squared: True
        sigonly: False

.statistics.distance:
  PairwiseDistance:
    labels:
      - unsigned
      - unordered
      - nonlinear
      - undirected
    dependencies:
    configs:
      - metric: "euclidean"
      - metric: "cityblock"
      - metric: "cosine"
      - metric: "chebyshev"
      - metric: "canberra"
      - metric: "braycurtis"

# Information-theoretic statistics
.statistics.infotheory:
  DirectedInfo: # No theiler window yet
    labels:
      - directed
      - nonlinear
      - unsigned
      - bivariate
      - time-dependent
    dependencies: 
      - java
    configs:
      - estimator: gaussian
      - estimator: kozachenko
      - estimator: kernel

  # Mutual information
  MutualInfo:
    labels:
      - undirected
      - nonlinear
      - unsigned
      - bivariate
      - contemporaneous
    dependencies: 
      - java
    configs:
      - estimator: gaussian

      - estimator: kraskov
        prop_k: 4

      - estimator: kraskov
        prop_k: 4
        dyn_corr_excl: AUTO

      - estimator: kernel
        kernel_width: 0.25

  # Mutual information
  TimeLaggedMutualInfo:
    labels:
      - directed
      - nonlinear
      - unsigned
      - bivariate
      - time-dependent
    dependencies: 
      - java
    configs:
      - estimator: gaussian

      - estimator: kraskov
        prop_k: 4

      - estimator: kraskov
        prop_k: 4
        dyn_corr_excl: AUTO

      - estimator: kernel
        kernel_width: 0.25

  # Transfer entropy
  TransferEntropy:
    labels:
      - directed
      - nonlinear
      - unsigned
      - bivariate
      - time-dependent
    dependencies: 
      - java
    configs:
      # Kraskov estimator with auto-embedding on source/target and DCE
      - estimator: kraskov
        prop_k: 4
        auto_embed_method: MAX_CORR_AIS
        k_search_max: 10
        tau_search_max: 4

      - estimator: kraskov
        prop_k: 4
        auto_embed_method: MAX_CORR_AIS
        k_search_max: 10
        tau_search_max: 4
        dyn_corr_excl: AUTO

      # Kraskov estimator with auto-embedding on target-only, src history of 1, and DCE
      - estimator: kraskov
        prop_k: 4
        k_history: 2
        l_history: 1
        dyn_corr_excl: AUTO

      # Kraskov estimator with fixed embedding of 1 for source/target and DCE
      - estimator: kraskov
        prop_k: 4
        k_history: 1
        l_history: 1
        dyn_corr_excl: AUTO

      # Same as above with no DCE
      - estimator: kraskov
        prop_k: 4
        k_history: 1
        l_history: 1

      # Currently the Kernel method has an overload issue with the AIS calculator..
      # Kernel estimator with auto-embedding on source/target and DCE
      # - estimator: kernel
      #   auto_embed_method: MAX_CORR_AIS
      #   k_search_max: 4
      #   kernel_width: 0.25

      # Kernel estimator with no auto-embedding on source/target and DCE
      - estimator: kernel
        kernel_width: 0.25
        k_history: 1
        l_history: 1

      # Gaussian estimator doesn't have DCE (aka Bartlett corrections) yet
      - estimator: gaussian
        auto_embed_method: MAX_CORR_AIS
        k_search_max: 10
        tau_search_max: 2

      - estimator: gaussian
        k_history: 1
        l_history: 1

      - estimator: symbolic
        k_history: 1
        l_history: 1

      - estimator: symbolic
        k_history: 10
        l_history: 1


# statistics that analyse in the frequency-domain (see Schoegl and Supp, 2006)
.statistics.spectral:
  CoherencePhase:
    labels:
      - undirected
      - linear
      - unsigned
      - bivariate
      - frequency-dependent
    dependencies:
    configs:
      - fs: 1

      - fmin: 0
        fmax: 0.25

      - fmin: 0.25
        fmax: 0.5

      - fs: 1
        statistic: max

      - fmin: 0
        fmax: 0.25
        statistic: max

      - fmin: 0.25
        fmax: 0.5
        statistic: max

  CoherenceMagnitude:
    labels:
      - undirected
      - linear
      - unsigned
      - bivariate
      - frequency-dependent
    dependencies:
    configs:
      - fs: 1

      - fmin: 0
        fmax: 0.25

      - fmin: 0.25
        fmax: 0.5

      - fs: 1
        statistic: max

      - fmin: 0
        fmax: 0.25
        statistic: max

      - fmin: 0.25
        fmax: 0.5
        statistic: max

  PhaseSlopeIndex:
    labels:
      - directed
      - linear/nonlinear
      - unsigned
      - bivariate
      - frequency-dependent
    dependencies:
    configs:
      - fmin: 0
        fmax: 0.5

      - fmin: 0
        fmax: 0.25

      - fmin: 0.25
        fmax: 0.5
