base_output_dir: data/case_2/
pyspi_config: configs/pyspi/case_2_config.yaml
pyspi_subset: default
normalise: false
rng_seed: 110305
save_heatmap: false
threads: 8

defaults:
  M_values: [8, 16]
  T_values: [800, 1600, 3200]
  instances: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
  # single_instance_M_values: [64]
  # single_instance_T_values: [1000]
  # single_instance_instances: [0]

mts_classes:
  - name: "VAR(1)-Symmetric"
    labels: ["linear", "gaussian", "var", "symmetric"]
    generator: "varma"
    include_base_variant: true
    base_params:
      phi: 0.6
      coupling: 0.2
      topology: "ring-symmetric" 
      ma_phi: 0.0
      ma_coupling: 0.0
      noise_std: 0.1
      transients: 100
      zscore: true
      target_rho: 0.99
    variants: []

  # CLASS 2: Unidirectional (Directed Information Flow)
  - name: "VAR(1)-Unidirectional"
    labels: ["linear", "gaussian", "var", "directed"]
    generator: "varma"
    include_base_variant: true
    base_params:
      phi: 0.6
      # Note: You might need to adjust coupling slightly if the loss of 
      # one neighbor drops the spectral radius too much, 
      # but the code handles rescaling automatically via target_rho.
      coupling: 0.2
      topology: "ring-unidirectional"
      ma_phi: 0.0
      ma_coupling: 0.0
      noise_std: 0.1
      transients: 100
      zscore: true
      target_rho: 0.99
    variants: []
