base_output_dir: data/case_3/
pyspi_config: configs/pyspi/case_3_config.yaml
pyspi_subset: default
normalise: false
rng_seed: 110305
save_heatmap: false
threads: 8

defaults:
  M_values: [8, 16]
  T_values: [500, 1000, 2000]
  instances: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
  # single_instance_M_values: [64]
  # single_instance_T_values: [1000]
  # single_instance_instances: [0]

mts_classes:
# CLASS A: Global Synchronization (Rigid)
  - name: "Kuramoto-Sync"
    labels: ["nonlinear", "oscillator", "synchronous", "rigid"]
    generator: "kuramoto"
    include_base_variant: false
    base_params:
      topology: "all-to-all"
      K: 4.0                # Strong coupling forces zero-lag sync
      dt: 0.05
      omega_mean: 1.0       # Arbitrary natural frequency
      omega_std: 0.05       # Low heterogeneity to ensure easy sync
      noise_std: 0.05
      transients: 1000
      zscore: true
    variants:
      - name: "base"
        params: {}

  # CLASS B: Traveling Wave (Elastic)
  - name: "Kuramoto-Wave"
    labels: ["nonlinear", "oscillator", "wave", "elastic"]
    generator: "kuramoto"
    include_base_variant: false
    base_params:
      topology: "ring-unidirectional"
      K: 2.0                # Sufficient to lock frequency, but forces phase offset
      dt: 0.05
      omega_mean: 1.0
      omega_std: 0.05
      noise_std: 0.05
      transients: 1000
      zscore: true
    variants:
      - name: "base"
        params: {}