mode: full
base_output_dir: data/full
pyspi_config: configs/blended_config.yaml
pyspi_subset: default
normalise: true
rng_seed: 110305
save_heatmap: false
threads: 8

defaults:
  M_values: [16, 32]
  T_values: [800, 1600]
  instances: [0, 1, 2]

mts_classes:
  - name: "VAR(1)_variants"
    labels: ["linear", "gaussian", "var"]
    generator: "varma"
    include_base_variant: false
    instances: [0]
    base_params:
      phi: 0.6
      coupling: 0.4
      ma_phi: 0.0
      ma_coupling: 0.0
      noise_std: 0.1
      transients: 100
    variants:
      - name: "phi-0.1_coupling-0.9"
        params: 
          phi: 0.1
          coupling: 0.9
      - name: "phi-0.9_coupling-0.1"
        params: 
          phi: 0.9
          coupling: 0.1
      - name: "phi-0.9_coupling-0.9"
        params: 
          phi: 0.9
          coupling: 0.9
      - name: "phi-0.1_coupling-0.1"
        params: 
          phi: 0.1
          coupling: 0.1
