mode: full
base_output_dir: data/full
pyspi_config: configs/blended_config.yaml
pyspi_subset: default
normalise: true
rng_seed: 110305
save_heatmap: false
threads: 8

defaults:
  M_values: [4, 8, 16, 32]
  T_values: [200, 400, 800, 1600]
  instances: [0, 1, 2, 3]

mts_classes:
  - name: "VAR(1)"
    labels: ["linear", "gaussian", "var"]
    generator: "varma"
    include_base_variant: false
    instances: [0, 1, 2, 3]
    base_params:
      phi: 0.6
      coupling: 0.2
      ma_phi: 0.0
      ma_coupling: 0.0
      noise_std: 0.1
      transients: 100
    variants:
      - name: "phi-0.6_coupling-0.2"
        params: {}  
  
  - name: "CML"
    labels: ["nonlinear", "cml"]
    generator: "cml_logistic"
    include_base_variant: false
    base_params:
      alpha: 1.7522
      eps: 0.00115
      delta: "3"
      transients: 0
    variants:
      - name: "spatiotemporal_intermittency_I"
        params:
          alpha: 1.7522
          eps: 0.00115
          delta: "1,3,12"
          transients: 0

  - name: "Kuramoto"
    labels: ["oscillator", "kuramoto", "phase"]
    generator: "kuramoto"
    base_params:
      dt: 0.1
      k: -4
      omega_mean: 0.5
      omega_std: 0.3
      eta: 0.0
      transients: 100
    include_base_variant: false
    instances: [0, 1, 2, 3]
    variants:
      - name: 
        params:
          connectivity: "all-to-all"

  - name: "Wave1D"
    labels: ["pde", "wave", "1d"]
    generator: "wave_1d"
    base_params:
      c: 10.0

  - name: "Wave2D"
    labels: ["pde", "wave", "2d"]
    generator: "wave_2d"
    M_values: [4, 9, 16, 25]
    base_params:
      c: 10.0

  - name: "GaussianNoise"
    labels: ["noise", "gaussian"]
    generator: "gaussian_noise"
    base_params: {}

  - name: "CauchyNoise"
    labels: ["noise", "cauchy", "heavy-tail"]
    generator: "cauchy_noise"
    base_params: {}

  - name: "ExponentialNoise"
    labels: ["noise", "exponential"]
    generator: "exponential_noise"
    base_params: {}
